# Run previous commits to pinpoint a failure's origin.
stepback: true

# Mark failures other than test failures with a purple box.
command_type: system

# Limit maximum test running time.
exec_timeout_secs: 3600

axes:
  - id: foo
    values:
      - id: bar

functions:
  "do it":
    - command: git.get_project
      params:
        directory: src
    - command: subprocess.exec
      params:
        working_dir: src
        command: git submodule update --init --recursive
    - command: shell.exec
      params:
        working_dir: src
        script: |
          export ATLAS_API_USERNAME="${atlas_key}"
          export ATLAS_API_PASSWORD="${atlas_secret}"
          bash run-python.sh

tasks:
  - name: do-it
    tags: ["all"]
    commands:
      - func: "do it"

buildvariants:
- matrix_name: test
  matrix_spec:
    foo: bar
  display_name: Test
  tasks:
    - ".all"
  run_on: rhel70-small
